---
- name: install guacamole related packages
  apt: 
    name: 
      - libcairo2-dev
      - libpng-dev
      - libtool-bin
      - libossp-uuid-dev
      - libavcodec-dev
      - libavformat-dev
      - libavutil-dev
      - libswscale-dev
      - freerdp2-dev
      - libpango1.0-dev
      - libssh2-1-dev
      - libvncserver-dev
      - libwebsockets-dev
      - libssl-dev
      - libwebp-dev
      - make
      - tomcat9
      - openjdk-11-jdk
      - libapr1-dev
    state: present
    update_cache: yes

- name: install Debian specific libjpeg-turbo
  apt: 
    name: 
      - libjpeg62-turbo-dev
    state: present
    update_cache: yes
  when: ansible_facts['distribution'] == "Debian"

- name: install Ubuntu specific libjpeg-turbo
  apt:
    name:
      - libjpeg-turbo8-dev
    state: present
    update_cache: yes
  when: ansible_facts['distribution'] == "Ubuntu"

- name: check for lock file
  stat:
    path: /var/tmp/guac.lock
  register: guacd_lock

- block:
  - name: Create guacamole directories
    file: 
      path: "{{ guacamole_file_structure }}"
      state: directory
    loop: 
      - /etc/guacamole
      - /etc/guacamole/build
      - /etc/guacamole/extensions
      - /etc/guacamole/lib
    loop_control:
      loop_var: guacamole_file_structure
  - name: Extract guacamole-server into /root/build/
    unarchive:
      src: guacamole-server-latest.tar.gz
      dest: /etc/guacamole/build/
  - name: Execute configure script
    shell: ./configure --with-init-dir=/etc/init.d
    args:
      chdir: /etc/guacamole/build/guacamole-server-1.3.0
  - name: Build guacamole-server from source
    make:
      chdir: /etc/guacamole/build/guacamole-server-1.3.0
  - name: Build guacamole-server from source
    make:
      chdir: /etc/guacamole/build/guacamole-server-1.3.0
      target: install
  - name: update installed binaries 
    shell: /sbin/ldconfig
  - name: create lock file for guacamole-server build
    file:
      path: /var/tmp/guac.lock
      state: touch
  when: guacd_lock.stat.exists == false 

- name: Start guacd and ensure start on boot
  systemd:
    name: guacd
    state: started
    enabled: yes
