---
- name: Wait For Webpage
  uri:
    url: "https://{{ nginx_server_name }}"
    method: GET
    validate_certs: no
  register: webpage
  until: webpage.status == 200
  retries: 10
  delay: 10
  run_once: true
  become: false
  delegate_to: 127.0.0.1
  
- name: Get JWT Token
  uri:
    url: https://{{ nginx_server_name }}/api/tokens
    method: POST
    body_format: form-urlencoded
    body:
      username: guacadmin
      password: guacadmin
    validate_certs: no
  register: login
  become: false
  delegate_to: 127.0.0.1
  run_once: true

- name: Setup ALL User Group
  uri:
    url: https://{{ nginx_server_name }}/api/session/data/mysql/userGroups?token={{ login.json.authToken }}
    method: POST
    body_format: json
    body: { "identifier": "ALL", "attributes": { "disabled": "" }}
    validate_certs: no
  become: false
  register: result
  delegate_to: 127.0.0.1
  run_once: true



