---
- name: import schema and create admin user
  include: mariadb.yml
  when: build_db is defined

- name: install and configure nginx for guacamole
  include: nginx.yml

- name: build guacamole server from source
  include: guacamole-server.yml

- name: deploy guacamole client war file
  include: guacamole-client.yml

- name: create initial groups via guac api
  include: guac-api.yml

