---
- name: install squid
  apt:
    name: 
      - squid
      - squidclient
    state: present
    update_cache: yes

- name: ensure squid is running
  systemd:
    name: squid
    state: started
    enabled: yes

- name: copy squid config
  template:
    src: squid.j2
    dest: /etc/squid/squid.conf
    owner: root
    group: root
    mode: 0644
  notify: restart squid
