---
- name: install pymysql, mariadb-server & mariadb-client
  apt:
    name: 
      - python3-pymysql
      - mariadb-server
      - mariadb-client
    state: present
    update_cache: true

- name: root password is present
  mysql_user:
    name: 'root'
    host_all: true
    password: '*70DC9DC508109F533FDA864A89F8AA87651BD544'
    encrypted: yes
    state: present
    login_unix_socket: "{{ login_unix_socket }}"

- name: install .my.cnf with credentials
  template:
    src: 'my-cnf.j2'
    dest: '/root/.my.cnf'
    mode: '0400'

- name: test database is absent
  mysql_db:
    name: test
    state: absent
    login_unix_socket: "{{ login_unix_socket }}"

- name: anonymous users are absent
  mysql_user:
    name: ''
    state: absent
    host_all: true
    login_unix_socket: "{{ login_unix_socket }}"

- name: remove remote root
  community.mysql.mysql_query:
    query:
      - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
    login_unix_socket: "{{ login_unix_socket }}"

- name: create database user for galera replication and guacamole 
  community.mysql.mysql_user:
    name: "{{ item }}"
    password: "{{ db_password }}"
    state: present
  loop: 
    - sst_user
    - "{{ db_username }}"

- name: template out galera cluster configuration
  template:
    src: z-galera.j2
    dest: /etc/mysql/mariadb.conf.d/z-galera.cnf

- name: stop mariadb daemon
  systemd:
    name: mariadb
    state: stopped
    enabled: true

- name: boot strap cluster
  command: /usr/bin/galera_new_cluster
  run_once: true
  when: "'enpx01' in group_names"

- name: start second cluster node
  systemd: 
    name: mariadb
    state: started
    enabled: true
  when: "'enpx02' in group_names"

- name: import guacamole database schema 
  block:
  - name: check for lock file 
    stat:
      path: /var/tmp/schema.lock
    register: sql_lock
  - name: copy sql files ready for import
    copy: 
      src: "{{ item }}"
      dest: /etc/mysql/
    loop:
      - 001-create-schema.sql
      - 002-create-admin-user.sql
  - name: create cpx database and create initial guacadmin user
    community.mysql.mysql_db:
      name: "{{ db_dbname }}"
      state: import
      target: "{{ item }}"
    loop: 
      - /etc/mysql/001-create-schema.sql
      - /etc/mysql/002-create-admin-user.sql
    run_once: true
    when: sql_lock.stat.exists == false
    register: sql_schema
  - name: create lock file for sql schema import
    file:
      path: /var/tmp/schema.lock
      state: touch
    when: sql_schema.changed == true

- name: grant rack user privileges to guacamole database
  community.mysql.mysql_query:
    login_db: "{{ db_dbname }}"
    query: GRANT SELECT,INSERT,UPDATE,DELETE ON cpx000db.* TO "{{ db_username }}"@"{{ db_endpoint }}"
  run_once: true
