plugin: aws_ec2
aws_profile: default
regions:
  - eu-west-2
filters:
  tag:Environment:
    - web
    - private
  instance-state-name : running
keyed_groups:
  - key: tags.Environment
    separator: ''
compose:
  db_endpoint: "'rds.iacdemos.com'" 
  nginx_server_name: "'aws.iacdemos.com'"
  squid_localnet: "'192.168.0.0/16'"
