---
- name: install pymysql & mariadb-client
  apt:
    name:
      - python3-pymysql
      - mariadb-client
    state: present
    update_cache: true
  delegate_to: 127.0.0.1
  run_once: true

- name: create cpx database and create initial guacadmin user
  community.mysql.mysql_db:
    name: "{{ db_dbname }}"
    state: import
    login_host: "{{ db_endpoint }}"
    login_user: "{{ db_username }}"
    login_password: "{{ db_password }}"
    target: "{{ item }}"
  loop: 
    - "{{ lookup('env', 'PWD') }}/roles/deploy/files/001-create-schema.sql"
    - "{{ lookup('env', 'PWD') }}/roles/deploy/files/002-create-admin-user.sql"
  delegate_to: 127.0.0.1
  run_once: true
  become: false
